image: node:12

stages:
  - test
  - tag
  - publish

include:
  - template: Code-Quality.gitlab-ci.yml

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test
  only:
    - branches

tag:
  stage: tag
  image: registry.gitlab.com/gitlab-org/release-cli
  script:
    - |
      VERSION=$(cat package.json | sed -n "s/^.*\"version\": \"\\(.*\\)\".*$/\1/p")
      DESCRIPTION=$(cat CHANGELOG.md | sed -e "1,/$(echo $VERSION | sed 's/\\./\\\\./')/d" | sed -e '/^## /,$d')
      CURRENT_TAG=$(git describe --tags 2>/dev/null || true)
      if [ "$CURRENT_TAG" != "v$VERSION" ]; then
        release-cli --server-url $CI_SERVER_URL --job-token $CI_JOB_TOKEN \
        --project-id $CI_PROJECT_ID create --name "Release v${VERSION}" \
        --description "$DESCRIPTION" --tag-name "v${VERSION}" \
        --ref $CI_COMMIT_SHA
      fi
  variables:
    GIT_SUBMODULE_STRATEGY: none
  only:
    - master@bytesnz/twitchdown

publish:
  stage: publish
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPMT}' > .npmrc
    - npm publish
  only:
    - master@bytesnz/twitchdown
